export const SUBMIT_EMERGENCY = 'SUBMIT_EMERGENCY';
export const EMERGENCIES_ERROR = 'EMERGENCIES_ERROR';
export const EMERGENCIES_LOADING = 'EMERGENCIES_LOADING';
export const EMERGENCIES_SUCCESS = 'EMERGENCIES_SUCCESS';
export const EMERGENCIES_CLEAR_RESPONSE = 'EMERGENCIES_CLEAR_RESPONSE';
export const STORE_EMERGENCY = 'STORE_EMERGENCY';
export const GET_ALL_EMERGENCIES = 'GET_ALL_EMERGENCIES';
